events {
}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    upstream upstream_norsk {
        server host.docker.internal:8080;
        keepalive 64;
    }

    upstream upstream_vis {
        server host.docker.internal:6791;
        keepalive 64;
    }

    upstream upstream_studio {
        server host.docker.internal:8000;
        keepalive 64;
    }

    server {
        listen [::]:443 ssl ipv6only=on;
        listen 443 ssl;
        http2 on;
        ssl_certificate /run/secrets/nginx.ec.crt;
        ssl_certificate_key /run/secrets/nginx.ec.key;
        include /etc/nginx/mime.types;

        # Studio
        # /live
        # /live/$nodeId/comms
        location ~ ^/studio/live(/.*)?$ {
            # auth_basic "Restricted";
            # auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://upstream_studio/live$1;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 3600;
            # Used to template `head/base` in `view.html` for components
            proxy_set_header X-Rewrite-URL $request_uri;
            # Push redirects under /studio too
            proxy_redirect / /studio/;
        }
        location ~ ^/studio/(.*)$ {
            # auth_basic "Restricted";
            # auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://upstream_studio/$1;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            # Push redirects under /studio too
            proxy_redirect / /studio/;
        }
        location ~ ^(/?|/studio)$ {
            return 301 /studio/;
        }
        # `nodeApiUrl()`/`componentApiUrl()` are (currently) hardcoded to the web root
        location ~ ^/(live|component)(/.*)?$ {
            return 308 /studio$request_uri;
        }

        # Norsk
        # (No websockets under the public web endpoints)
        location ~ ^/norsk/(.*)$ {
            proxy_pass http://upstream_norsk/$1;
        }
        location ~ ^/norsk$ {
            return 301 /norsk/;
        }

        # Visualiser and hosted Norsk docs
        # /uvis/ws
        # /status
        location ~ ^/((?:.*/)?(?:ws|status))$ {
            # auth_basic "Restricted";
            # auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://upstream_vis$request_uri;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_read_timeout 3600;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        # /visualiser/ -> :6791/visualiser/
        # /uvis/ -> :6791/uvis/
        location ~ ^/(visualiser|uvis|docs)(/.*)?$ {
            # auth_basic "Restricted";
            # auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://upstream_vis$request_uri;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            # Do not proxy redirects
        }
    }

    server {
        return 301 https://$host$request_uri;

        listen 80;
        listen [::]:80;
    }
}
