########################################################################
# This is the main docker-compose file for Norsk Studio and Norsk Media
# It describes everything other than network type (host or docker)
# and the ports to be shared in docker networking
########################################################################
version : “3”

services:
  #################################################################
  # Norsk Media Server
  #################################################################
  norsk-media:
    container_name: norsk-media
    image: norskvideo/norsk:v1.0.365-main
    command: --license-file /run/secrets/license.json
    # CEF (needs a large amount of shared memory)
    shm_size: '2gb'
    # privileged: true
    restart: always
    volumes:
      - ../mnt:/mnt
      - /dev/shm:/dev/shm/
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://127.0.0.1:6791"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    secrets:
      - license.json

    ###############################################################
    # Provide access to any devices Norsk Media might need to access
    ###############################################################
    # devices:
    #   - /dev/nvme0n1 # NETINT Quadra
    #   - /dev/nvme1n1 # More Quadra
    #   - /dev/flex-x4100 # Deltacast SDI
    #   - /dev/ama_transcoder1 # AMD MA35D
    ###############################################################
    # Same for NVIDIA
    # runtime: nvidia
    ###############################################################
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=all

    ###############################################################
    # The below are nothing to do with Norsk itself, but
    # are fields we often set in production settings...
    ###############################################################

    # Manage ownership of mounted volumes
    # user: ${USER_ID}:${GROUP_ID}

    # Manage which cores this container runs on
    # Useful for segregating Norsk instances on large servers...
    # cpuset: 0-31

  #################################################################
  # Norsk Studio
  #################################################################
  norsk-studio:
    container_name: norsk-studio
    image: norskvideo/norsk-studio-starter-kit:latest
    # image: norsk-studio-starter-kit:latest
    # restart: always
    depends_on:
      norsk-media:
        condition: service_healthy
    volumes:
      - ../mnt:/mnt
    command: npx studio-editor
    env_file:
      - ../envs/studio-env # Environment variables used by Norsk Studio
      - ../envs/components-env # Environment variables used by Norsk Studio's components
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://127.0.0.1:8000"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

    ###############################################################
    # The below are nothing to do with Norsk Studio itself, but
    # are fields we often set in production settings...
    ###############################################################

    # Manage ownership of mounted volumes
    # user: ${USER_ID}:${GROUP_ID}


    # Below are fields we often set in production settings...

    # Useful for segregating Norsk instances on large servers...
    # cpuset: 0-1

secrets:
  license.json:
    file: ../secrets/license.json