version : “3”

networks:
  norskNetwork:
    name: norsk-nw

services:
  norsk-studio:
    container_name: norsk-studio
    # image: norskvideo/norsk-studio-starter-kit:0.0.2
    image: norsk-studio-starter-kit:latest
    # restart: always
    depends_on:
      norsk:
        condition: service_healthy
    volumes:
      - ../mnt:/mnt
    command: npx studio-editor ${INITIAL_STUDIO_DOCUMENT}
    env_file:
      - envs/studio-env # Environment variables used by Norsk Studio
      - envs/components-env # Environment variables used by Norsk Studio's components
    environment:
      # In Docker networking the name of the norsk server is norsk - not 127.0.0.1
      STUDIO_NORSK_HOST: norsk
    ports:
      - ${STUDIO_PORT:-8000}:8000
      # Any external ports needed by Studio components.
      - 5000:5000 # E.g. dynamic bug update port
    # Useful for segregating Norsk instances on large servers...
    # cpuset: ${CPU_SET:-0-31}
    networks:
      - norskNetwork
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:8000"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
  norsk:
    container_name: norsk-server
    image: norskvideo/norsk:v1.0.365-main
    command: --license-file /mnt/license/license.json
    # CEF (needs a large amount of shared memory)
    shm_size: '2gb'
    # privileged: true
    restart: always
    # user: ${USER_ID}:${GROUP_ID}
    # Useful for segregating Norsk instances on large servers...
    # cpuset: ${CPU_SET:-0-31}
    ports:
      # "rtmp"
      - 1935:1935/TCP
      # "srt-1"
      - 5001:5001/UDP
      # "srt-2"
      - 5002:5002/UDP
      # "norsk-media-ui"
      - 6791:6791/TCP
      # "media-serving"
      - 8080:8080/TCP
    networks:
      - norskNetwork
    volumes:
      - ../mnt:/mnt
      - /dev/shm:/dev/shm/
    # devices:
    #   Provide access to server hardware - you device names may be different
    #   - /dev/nvme0n1 # NETINT Quadra
    #   - /dev/nvme1n1 # More Quadra
    #   - /dev/flex-x4100 # Deltacast SDI
    #   - /dev/ama_transcoder1 # AMD MA35D
    # environment:
    #   DEFAULT_QUADRA_DEVICE_INDEX: ${DEFAULT_QUADRA_DEVICE_INDEX:-0}
    #   ERL_ZFLAGS: "+SDio 32 +S 32:32" # Optional Erlang tuning
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:6791"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
