services:
  turn:
    container_name: norsk-turn
    image: coturn/coturn
    # user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - ../turn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    ports:
      - 3478:3478/udp # STUN/TURN
      - 3478:3478/tcp # TURN tcp transport
      - 5349:5349/tcp # tls
      - 5349:5349/udp # tls
      - 59160-59200:59160-59200/udp  # UDP relay
    networks:
      - norskNetwork