apiVersion: apps/v1
kind: Deployment
metadata:
  name: norsk-studio
  labels:
    app.kubernetes.io/name: norsk-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: norsk-studio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: norsk-studio
    spec:
      volumes:
        - name: norsk-secrets
          secret:
            secretName: norsk-secrets

        - name: norsk-pv-storage
          persistentVolumeClaim:
            claimName: norsk-pv-claim
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2G
      containers:

        #################################################################
        # Norsk Media Server
        #################################################################
        - name: norsk-media
          image: norskvideo/norsk:v1.0.365-main
          args:
            - --license-file
            - /run/secrets/license.json
          ports:
            - name: "rtmp"
              containerPort: 1935
              hostPort: 1935
              protocol: TCP
            - name: "srt-1"
              containerPort: 5001
              hostPort: 5001
              protocol: UDP
            - name: "srt-2"
              containerPort: 5002
              hostPort: 5002
              protocol: UDP
            - name: "norsk-media-ui"
              containerPort: 6791
              hostPort: 6791
              protocol: TCP
            - name: "media-serving"
              containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - name: norsk-secrets
              mountPath: /run/secrets
            - name: norsk-pv-storage
              mountPath: "/mnt"
            # CEF (needs a large amount of shared memory)
            # This is the equivalent of Docker's: shm_size: '2gb'
            - name: dshm
              mountPath: /dev/shm

        #################################################################
        # Norsk Studio
        #################################################################
        - name: norsk-studio
          # image: norskvideo/norsk-studio-starter-kit:latest
          image: localhost:32000/norsk-studio-starter-kit:latest
          args:
            - npx
            - studio-editor
          env:
            - name: NODE_ENV
              value: kubernetes
            - name: NODE_DEBUG
              value: ${NODE_DEBUG}
            - name: LOG_LEVEL
              value: ${LOG_LEVEL}
            - name: STUDIO_WORKING_DIRECTORY
              value: ${STUDIO_WORKING_DIRECTORY}
            - name: STUDIO_DOCUMENT
              value: ${STUDIO_DOCUMENT}
            - name: NORSK_HOST
              value: 127.0.0.1
            - name: PUBLIC_URL_PREFIX
              value: ${PUBLIC_URL_PREFIX}
          ports:
            - name: "studio-ui"
              containerPort: 8000
              protocol: TCP
              hostPort: 8000
          volumeMounts:
            - mountPath: "/mnt"
              name: norsk-pv-storage
