apiVersion: v1
kind: Service
metadata:
  name: norsk-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: norsk-studio
  ports:
    - name: "rtmp"
      port: 1935
      targetPort: 1935
      protocol: TCP
    - name: "srt-1"
      port: 5001
      targetPort: 5001
      protocol: UDP
    - name: "srt-2"
      port: 5002
      targetPort: 5002
      protocol: UDP
    - name: "norsk-media-ui"
      port: 6791
      targetPort: 6791
      protocol: TCP
    - name: "media-serving"
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: "studio-ui"
      port: 8000
      targetPort: 8000
      protocol: TCP